### ISSUE TITLE
Idea: scripting engine

### ISSUE THREAD

**Issue by tom-sherman** [astrenoxcoop/supercell#4]
Thought I'd kick some discussion off about this.

There's a conceptual question about supercell which is: how does it allow extension of matchers and custom matchers?

I think the most natural answer is a scripting engine. I've been playing around with embedding [boa](https://boajs.dev/) (a rust-based minimal JS runtime) into supercell that you could use in a couple of different ways.

```yaml
# Inline expression
- type: script
  code: 'record.did.startsWith("did:web:")'

# External module
- type: script
  module: ./matcher.mjs
```

And then matcher.mjs looks like this:

```js
import { getProfile } from "./bsky-api.mjs"

export async function matcher(record) {
  const profile = await getProfile(record.did)

  return profile.description.includes("github.com")
}
```

Of course it doesn't have to be JS, that's just my preference 😅
